# Site settings
title: CpX's blog
email: pxchencoder@gmail.com
description: LLAP
baseurl: ""
url: "http://cccpx.github.io"
twitter_username: CCCCpX
github_username:  CCCpX

# Build settings
markdown: kramdown
