# Site settings
title: CpX's blog
email: pxchencoder@gmail.com
description: LLAP
baseurl: ""
url: "https://cccpx.github.io"
twitter_username: CpX
github_username:  CCCpX

# Build settings
markdown: kramdown
